### ISSUE TITLE
$vssHeight and other computed vars do not work

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [johndatserakis/vue-screen-size#3]
... but the functions themselves work when called directly e.g. `this.getScreenWidth()` 👍

**Comment by johndatserakis** [comment]
Hmm, that's strange. It's confirmed working in the latest [demo](https://johndatserakis.github.io/vue-screen-size/). Perhaps you could try upgrading to the latest version.

Closing this for now, will reopen if needed. Thank you.
