### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by atymic** [johndatserakis/vue-screen-size#4]
Seems to be broken on vue3

```
> node_modules/vue-screen-size/dist/vue-screen-size.esm.js:1:7: error: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
    1 │ import Vue from 'vue';
      ╵        ~~~

error when starting dev server:
Error: Build failed with 1 error:
node_modules/vue-screen-size/dist/vue-screen-size.esm.js:1:7: error: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
```

**Comment by johndatserakis** [comment]
Hey there - sorry yea I don't think this plugin will work out of the box with Vue 3. I haven't used Vue 3 yet really so I'm not sure. You could take a stab at forking this to try and update the export method. If I have time coming up I'll make an attempt, I'm just a tad busy now, sorry.

**Comment by johndatserakis** [comment]
Hey again - `vue-screen-size` has now been updated to be compatible with Vue 3. Vue 3 is supported from `v2.0.0` and beyond (current master). To use `vue-screen-size` with Vue 2, use `v1.0.1`.
